### ISSUE TITLE
Rollup is nice for libraries and simple apps, but...

### ISSUE THREAD

**Issue by trusktr** [pschroen/alien.js#1]
It doesn't (and never will) have things like module splitting and dynamic import (f.e. for loading certain code only when certain parts of the UI should be visible (f.e. if you show different UI based on client-side routes)).

Webpack is more complex, but it does have support for this, which for large apps can drastically reduce initial load time, and let the application only load bits and pieces as needed, otherwise never load un-used parts of the app.

**Comment by trusktr** [comment]
By the way, nice project. 😄

**Comment by pschroen** [comment]
Thanks, and good question.

My understanding right now is Webpack is better for websites and Rollup is better for libraries and frameworks.

Much of the Alien.js structure is modelled after three.js, which also uses Rollup. The idea is to keep it simple, and build websites like a framework.

The files in the `build` directory are meant for a future update where the classes can be used like a library. For the time being the process is importing from a submodule.

Open to exploring features like HMR (Hot Module Replacement)... I'll add that to the Roadmap. The plan for the Docs is to make it interactive, with dynamic importing of classes.

Cheers! 😄

**Comment by pschroen** [comment]
Finally releasing r18, a complete rewrite and refactored to be more of a project template with all the latest features, code-splitting, dynamic imports and class fields.
