### ISSUE TITLE
not showing on Ipad ?

### ISSUE THREAD

**Issue by cyrstem** [pschroen/alien.js#13]
Hey is it there a specific reason  why the  example : https://alien.js.org/examples/transitions/camera/ works on the iphone but not on ipad ?

**Comment by pschroen** [comment]
I'll have to take a look on my iPad to confirm though it's likely a difference in the versions of iOS, if you haven't updated the iPad in awhile?

The examples aren't transpiled with Babel anymore, so the code is running natively in the browser and would require Safari 14.1 or higher.

https://caniuse.com/mdn-javascript_classes_static_class_fields

**Comment by cyrstem** [comment]
> i'll try to check on a newer ipad then mine its old i guess but has no updates pending i was trying on Chrome for ipad v 92

so you where right it has to be with the IOS version 
i have a  question if you have time to answer or guide me 
i'm trying to implement a landing scene before  arriving to something   like this example  https://alien.js.org/examples/transitions/camera/  any advice of how to approach something like that ?

**Comment by DennisSmolek** [comment]
> i'm trying to implement a landing scene before arriving to something like this example https://alien.js.org/examples/transitions/camera/ any advice of how to approach something like that ?

Can you clarify "A landing Scene?"
Do you mean an animation where something lands?

I ask because it's common in apps like three or other 3D to call the world space a "scene"

Also, because your question doesn't relate to the problem you reported, it's helpful to the lib if you mark the issue as closed..

We can still chat on it, but it looks/tracks better

**Comment by cyrstem** [comment]
@DennisSmolek  i guess what i meant is how to have multiple scenes and managed them , when you build a  new projectlikie this```
 `npx degit pschroen/alien.js my-app
cd my-app
npm i`
```
 you get by default  a file call landing Scene i thought about it as a intro scene
but yeah that was  not related to this issue

**Comment by pschroen** [comment]
@DennisSmolek @cyrstem yes we can close this issue and I'll open another for an example of transitioning between scenes.

Thanks guys!
