### ISSUE TITLE
What's ScreenProjection for?

### ISSUE THREAD

**Issue by trusktr** [pschroen/alien.js#2]
https://github.com/pschroen/alien.js/blob/6dccdfc2f9605f9057303186acbaa03e46f30128/src/three/ScreenProjection.js#L11

What do you use this for?

**Comment by pschroen** [comment]
`ScreenProjection` converts screen coordinates to an object position and vice-versa. I'm in the process of working on an example for this, plus the Docs.

It's used like this:

```js
const projection = new ScreenProjection(camera);
const screen = new Vector2();

obj.position.copy(projection.unproject(screen));
```

And back again:

```js
screen.copyFrom(projection.project(obj.position));
```

**Comment by pschroen** [comment]
Finally releasing r18, a complete rewrite and refactored to be more of a project template with minimal classes, `ScreenProjection` has been removed with this release though I may still add it back in a future example update.
