### ISSUE TITLE
build - include non-singleton version

### ISSUE THREAD

**Issue by huygn** [pschroen/alien.js#4]
My use case is that I need to use es5 but I don't want the singleton style as I'm trying to integrating with Vuejs.

**Comment by pschroen** [comment]
There is a non-singleton version in the works to support ES6 without transpilation.

An alternative might be using alien.js as a UMD (Universal Module Definition). There's a `umd` example in `examples` for this use case, which I've used in a React project.

```js
// index.jsx
import Project from 'project';
// ...

new Project({ container: document.body });
```

```js
// src/Main.js
class Main {

    constructor({ container }) {

        container.appendChild(Stage.element);
        // ...
    }
}

export default Main;
```

**Comment by huygn** [comment]
When importing from `alien.js/src/Alien` or any none-es5 in `build` dir, I got `Class constructor Interface cannot be invoked without 'new'` error.

**Comment by pschroen** [comment]
The example above is for importing an ES5 UMD file that's been built with the `singletons()` plugin enabled, you shouldn't get an error if you import `examples/umd/build/project.js` into your project for example.

If you want to import the alien.js classes directly from `alien.js/src/Alien` into your Vue.js project, ya we'll need to remove that `singletons()` plugin. I'll post an update here once that's done.

**Comment by huygn** [comment]
Yea hence I have come up with #5, wouldn't that be sufficient?

**Comment by pschroen** [comment]
If that's working for you in the meantime that's great, the plan is to remove the plugin all-together shortly. I'll keep you posted here. Thanks!

**Comment by huygn** [comment]
Thanks! 👍

**Comment by pschroen** [comment]
Alright I've finally committed a large events and modules update I've been working on which should resolve this. See commit 9ba063c now on both the `dev` and `master` branches. Let me know if this works for your use case. Cheers!
